[package]
name = "cargo-bevy-mod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.22"
clap = { version = "3.2.17", features = ["derive"] }
dialoguer = "0.10.2"
toml_edit = "0.14.4"
